### ISSUE TITLE
Consider using functions instead of a class with static methods

### ISSUE THREAD

**Issue by marcioAlmada** [Seldaek/cli-prompt#1]
I'm probably being a PITA now that you already released v1, but consider this next time.

``` php
Seld\CliPrompt\prompt();
Seld\CliPrompt\hiddenPrompt($fallback = false);
```

**Comment by marcioAlmada** [comment]
I'm probably being a PITA now that you already released v1, but consider this next time.

**Comment by Seldaek** [comment]
Given that php has on function autoloading I'd say nope. You save a few characters but you include a file every time for possibly nothing so it's not amazing. I guess for a CLI-focused lib it'd be alright but oh well..
